= Spring Data Build Infrastructure image:https://img.shields.io/badge/Revved%20up%20by-Develocity-06A0CE?logo=Gradle&labelColor=02303A["Revved up by Develocity", link="https://ge.spring.io/scans?search.rootProjectNames=Spring Data Build"]

This repository contains common infrastructure to be used by Spring Data modules that build with Maven. It consists of a _resources_ project that bundles up resources that are needed during the build CSS for reference documentation generation and JavaDoc. The second project is _parent_ that can be used as parent project to pre-configure core dependencies, properties, reference documentation generation and most important of all the appropriate distribution assembly.

The parent project can be eased for either a single-module Maven project or a multi-module one. Each of the setups requires a slightly different setup of the project.

== Code of Conduct

This project is governed by the link:https://github.com/spring-projects/.github/blob/main/CODE_OF_CONDUCT.md[Spring Code of Conduct]. By participating, you are expected to uphold this code of conduct. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

== Project setup

=== General setup

The parent project configures the following aspects of the project build:

Shared resources are pulled in from the `spring-data-build-resources` dependency (images, CSS, JavaScript). Renders reference documentation from Asciidoc file named `index.adoc` within `src/asciidoc`. In the `distribute` profile, two assemblies are generated: A ZIP to be uploaded to docs.spring.io (incl. javadoc (browsable), reference docs as described before) with the following content:

[source]
----
- notice.txt
+ reference -> Asciidoc generated reference documentation
  + html
  + pdf
  + epub
+ api -> JavaDoc
----

A second ZIP is generated to be uploaded to docs.spring.io to contain all Spring namespace XSDs.

The following dependencies are pre-configured.

* Logging dependencies: SLF4j + Commons Logging bridge and Logback as test dependency
* Test dependencies: JUnit / AssertJ / Hamcrest / Mockito
* Dependency versions for commonly used dependencies

=== Single project setup

If the client project is a project consisting of a single project only all that needs to be done is declaring the parent project:

[source,xml]
----
<parent>
	<groupId>org.springframework.data.build</groupId>
	<artifactId>spring-data-parent</artifactId>
	<version>${most-recent-release-version}</version>
</parent>
----

Be sure to adapt the version number to the latest release version. The second and already last step of the setup is to activate the assembly and asciidoctor plugin in the build section:

[source,xml]
----
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-assembly-plugin</artifactId>
</plugin>
<plugin>
	<groupId>org.asciidoctor</groupId>
	<artifactId>asciidoctor-maven-plugin</artifactId>
</plugin>
----

As an example have a look at the build of https://github.com/spring-projects/spring-data-jpa[Spring Data JPA].

=== Multi project setup

A multi-module setup requires slightly more setup and some structure being set up.

* The root `pom.xml` needs to configure the `project.type` property to `multi`.
* Asciidoc documentation sources need to be in the root project.
* The assembly needs to be build in a dedicated sub-module (e.g. `distribution`), declare the assembly plugin (see single project setup) in that submodule and reconfigure the `project.root` property in that module to `${basedir}/..`.
* Configure `${dist.id}` in the root project to the basic artifact id (e.g. `spring-data-mongodb`) as this will serve as file name for distribution artifacts, static resources etc. It will default to the artifact id and thus usually resolve to a `…-parent` if not configured properly.

As an example have a look at the build of https://github.com/spring-projects/spring-data-mongodb[Spring Data MongoDB].

== Build configuration

* Goals to execute `clean (dependency:tree) install -Pci` to run the build
* Goals to execute `clean deploy -Pci,artifactory` to deploy artifacts to Artifactory
* A nightly build can then use `clean (dependency:tree) deploy -Pdistribute` to publish reference documentation

== Additional build profiles

* `ci` - Packages the JavaDoc as JAR for distribution (needs to be active on the CI server to make sure we distribute JavaDoc as JAR).
* `antora` - Creates Antora documentation.
* `distribute-schema` - Creates schema file distribution.
* `spring…-next` - Configures the Spring version to be used to be the next Spring Framework snapshot version.

== License

Spring Data Build is Open Source software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
