name: Setup and Start MongoDB
description: 'Initialize a MongoDB server looking up a configuration managed version pointing to a dedicated revision'

inputs:
  version:
    description: 'Desired MongoDB Server version'
    required: false
    default: 'latest'
  replica-set:
    description: 'Replica Set name (if not provided Mongo will be started as a standalone instance)'
    default: ''
    required: false

runs:
  using: composite
  steps:
    - uses: spring-projects/spring-data-build/actions/env-config@3.5.x
      id: ci-properties
      name: Load CI properties
    - name: Mongo Version
      id: determine-mongo-version
      shell: bash
      env:
        INPUT_VERSION: '${{ inputs.version }}'
      run: |
        MONGODB_VERSION=$(echo "${CONFIG_JSON}" | jq -r ".database.mongodb[\"${INPUT_VERSION}\"]")
        if [[ -z "${MONGODB_VERSION}" ]] || [[ "${MONGODB_VERSION}" == "null" ]]; then
          MONGODB_VERSION="${INPUT_VERSION}"
        fi
        echo "MONGODB_VERSION=${MONGODB_VERSION}" >> $GITHUB_OUTPUT
    - name: Start MongoDB Standalone
      shell: bash
      env:
        MONGODB_VERSION: '${{ steps.determine-mongo-version.outputs.MONGODB_VERSION }}'
      if: ${{ inputs.replica-set == '' }}
      run: docker run --rm -d -p 27017:27017 --name mongo "mongo:${MONGODB_VERSION}" --bind_ip_all
    - name: Start MongoDB Replica Set
      id: start-mongodb-replica-set
      shell: bash
      env:
        MONGODB_VERSION: '${{ steps.determine-mongo-version.outputs.MONGODB_VERSION }}'
        RS: '${{ inputs.replica-set }}'
      if: ${{ inputs.replica-set != '' }}
      run: |
        docker run --rm -d -p 27017:27017 --name mongo "mongo:${MONGODB_VERSION}" --replSet "${RS}" --bind_ip_all
        MONGO_CONTAINER_ADDR=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mongo)
        echo "MONGO_CONTAINER_ADDR=${MONGO_CONTAINER_ADDR}" >> $GITHUB_OUTPUT
    - name: Initialize MongoDB Replica Set
      shell: bash
      env:
        MONGODB_VERSION: '${{ steps.determine-mongo-version.outputs.MONGODB_VERSION }}'
        MONGO_CONTAINER_ADDR: '${{ steps.start-mongodb-replica-set.outputs.MONGO_CONTAINER_ADDR }}'
        RS: '${{ inputs.replica-set }}'
      if: ${{ inputs.replica-set != '' }}
      run: |
        sleep 5 # Give mongo a chance to start up
        docker run --rm mongo:${MONGODB_VERSION} mongosh --host "${MONGO_CONTAINER_ADDR}" --eval "rs.initiate({_id: \"${RS}\", members: [{_id: 0, host: \"${MONGO_CONTAINER_ADDR}:27017\"}]})"

