name: 'Setup Java JDK and Maven for Develocity usage'
description: 'Set up a version of the Java JDK and add the command-line tools to the PATH and prepare MAVEN_OPTS environment for Develocity usage'

inputs:
  java-version:
    description: 'The Java version to set up. Takes main, next, or a whole or semver Java version.'
    required: false
    default: 'main'
  develocity-access-key:
    description: 'Develocity access key. Should be set to a secret containing the Develocity Access key.'
    required: false

runs:
  using: composite
  steps:
    - uses: spring-projects/spring-data-build/actions/setup-java@4.0.x
      with:
        java-version: '${{ inputs.java-version }}'
    - name: Determine Development line
      id: determine-dev-line
      shell: bash
      run: |
        DEV_LINE=""
        if [[ -f "pom.xml" ]]; then
          DEV_LINE=$(python3 -c "import sys, re, xml.etree.ElementTree as ET; [print(re.search(r'((\d+)\.(\d+))\.', e.text).group(1)) for e in ET.parse(sys.stdin).findall('./{http://maven.apache.org/POM/4.0.0}version')]" < pom.xml)
        fi
        if [[ "DEV_LINE" == "" ]]; then
            DEV_LINE="x.y"
        fi
        echo "DEV_LINE=${DEV_LINE}" >> $GITHUB_OUTPUT
    - name: Maven Repository Cache
      uses: actions/cache@v5.0.3
      with:
        path: |
          ~/.m2/repository
          ~/.m2/wrapper
        key: ${{ runner.os }}-maven-${{ steps.determine-dev-line.outputs.DEV_LINE }}-${{ github.job }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ steps.determine-dev-line.outputs.DEV_LINE }}-${{ github.job }}-
          ${{ runner.os }}-maven-
    - name: Setup Develocity Maven Capturing
      uses: gradle/develocity-actions/setup-maven@1d6b56bc8352f11400f1d802d627dee852b3e946 #v2.1
      with:
        develocity-url: 'https://ge.spring.io'
        develocity-access-key: '${{ inputs.develocity-access-key }}'
        add-pr-comment: false
    - name: Set Env Variables
      shell: bash
      env:
        BUILD_USER_NAME: ${{ env.BUILD_USER_NAME }}
        ORIG_MAVEN_OPTS: ${{ env.MAVEN_OPTS }}
      run: |
        echo "MAVEN_OPTS=-Duser.name=${BUILD_USER_NAME} ${ORIG_MAVEN_OPTS}" >> "$GITHUB_ENV"
