name: 'Setup Java JDK'
description: 'Set up versions of the Java JDK and add the command-line tools to the PATH'

inputs:
  java-version:
    description: 'The Java version to set up. Takes main, next, latest, or a whole or semver Java version.'
    required: false
    default: 'main'

runs:
  using: composite
  steps:
    - uses: spring-projects/spring-data-build/actions/env-config@main
      id: ci-properties
      name: Load CI properties
    - name: Check if Java version is pre-configured
      id: check-java-version
      shell: bash
      env:
        JAVA_VERSION_INPUT: '${{ inputs.java-version }}'
      run: |
        # Example: check if a JSON field meets a condition
        PRECONFIGURED_JAVA_VERSION_EXISTS=$([[ "${JAVA_VERSION_INPUT}" =~ ^[a-z0-9\\.]+$ ]] && echo ${CONFIG_JSON} | jq -r ".java | has(\"${JAVA_VERSION_INPUT}\")")
        PRECONFIGURED_JAVA_VERSION=$([[ "${JAVA_VERSION_INPUT}" =~ ^[a-z0-9\\.]+$ ]] && echo ${CONFIG_JSON} | jq -r ".java.${JAVA_VERSION_INPUT}")
        echo "PRECONFIGURED_JAVA_VERSION_EXISTS=$PRECONFIGURED_JAVA_VERSION_EXISTS" >> $GITHUB_OUTPUT
        echo "PRECONFIGURED_JAVA_VERSION=$PRECONFIGURED_JAVA_VERSION" >> $GITHUB_OUTPUT
    - uses: actions/setup-java@v5.2.0
      id: install-preconfigured-java-version
      if: ${{ steps.check-java-version.outputs.PRECONFIGURED_JAVA_VERSION_EXISTS == 'true' }}
      with:
        java-version: '${{ steps.check-java-version.outputs.PRECONFIGURED_JAVA_VERSION }}'
        distribution: '${{ env.JAVA_DIST }}'
    - uses: actions/setup-java@v5.2.0
      id: install-custom-java-version
      if: ${{ steps.check-java-version.outputs.PRECONFIGURED_JAVA_VERSION_EXISTS == 'false' }}
      with:
        java-version: '${{ inputs.java-version }}'
        distribution: '${{ env.JAVA_DIST }}'

